name: Build and Push Docker image to Docker Hub

on: 
 push:
  branches:
   - master
   - release/*
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: https://hub.docker.com/repository/docker/lakshmi5382/jensensweatherapp/general
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install --file pom.xml
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker-compose build --no-cache --force-rm
  test:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: Test the Docker image
         run: docker-compose up -d
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven'

      - name: Build with Maven
        run: mvn clean install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}"
          push: true
          tags:  ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: image digest
        run: echo ${{ steps.build-and-push.outputs.digest }}
      - name: image digest
        run: echo ${{ steps.build-and-push.outputs.digest }}
